---
output:
  html_document:
    theme: cerulean
params:
  directory:
    label: "Directory to look for data files:"
    value: "H: drive"
    input: radio
    choiceNames: ["../data", "Desktop", "Other - must specify full path in filename, below"]
    choiceValues: ["H: drive", "Desktop", "Other"]
  filename: 
    label: "AirVision filename:" 
    value: "ExportCalibrationReport.csv"
  comment: 
    label: "Comment (optional):"
    value: ""
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
## load libs abd global params...

knitr::opts_knit$set(width=90)
knitr::opts_chunk$set(comment="", fig.width=8, fig.height = 5, echo = FALSE, warning=FALSE, message=FALSE )

library(dplyr, warn.conflicts=FALSE )

## get filename and path, comment text:
filename <- params$filename
comment <- params$comment

dir <- params$directory
if(dir == "H: drive") dir <- paste0(getwd(), "/data/")
if(dir == "Desktop") {
  path <- strsplit(path.expand("~"), "/")[[1]]
  path <- path[1:(length(path)-1)]
  path <- paste(path, collapse = "/")
  dir <- paste(path, "Desktop/", sep = "/")
} 
if(dir == "Other") {
  path <- strsplit(filename,"\\", fixed = TRUE)[[1]]
  dir <- paste0(path[-length(path)], collapse = "/")
  dir <- paste0(dir, "/")
  filename <- path[length(path)]
  rm(path)
} 
## check inputs and load datafile:
# check AirVision file is present
if(!filename %in% list.files(dir)) {
  stop(paste0("File ", filename, " not found in ", dir, "."), call. = FALSE)
} 

# load data: if .txt then TAB delimited, if .csv then comma.
if(substr(filename, nchar(filename)-3, nchar(filename))==".txt"){
  d <- read.table(paste0(dir,filename), as.is = TRUE, header=T, sep="\t")
} else {
  d <- read.table(paste0(dir,filename), as.is = TRUE, header=T, sep=",")
}

# format data:
d<-d[,-c(6,10)]
names(d)<-c("site", "parameter", "seq", "phase", "date", "response", "true", "error")
d$date<-as.POSIXct(d$date, tz="UTC", format="%d-%b-%Y %H:%M:%S")

# remove trailing spaces--necessary for .txt files:
rmspace <- function(a) gsub("[[:space:]]*$", "", a)
d$parameter <- sapply(d$parameter, rmspace)
d$seq <- sapply(d$seq, rmspace)
d$phase <- sapply(d$phase, rmspace)

##Standardize parameter,seq, & site names
if(("Mesa 2" %in% unique(d$site))==TRUE) {d$site[which(d$site=="Mesa 2")]<-"zMesa_cals"}
if(("O3-cal" %in% unique(d$parameter))==TRUE) {d$parameter[which(d$parameter=="O3-cal")]<-"O3CAL"}
if(("NO-cal" %in% unique(d$parameter))==TRUE) {d$parameter[which(d$parameter=="NO-cal")]<-"NOCAL"}
if(("NO2-cal" %in% unique(d$parameter))==TRUE) {d$parameter[which(d$parameter=="NO2-cal")]<-"NO2CAL"}
if(("NOx-cal" %in% unique(d$parameter))==TRUE) {d$parameter[which(d$parameter=="NOx-cal")]<-"NOXCAL"}
if(("NOXCON" %in% unique(d$parameter))==TRUE) {d$parameter[which(d$parameter=="NOXCON")]<-"NOXCony"}
if(("SO2" %in% unique(d$parameter))==TRUE) {d$parameter[which(d$parameter=="SO2")]<-"SO2-CAL"}
if(("ZSP" %in% unique(d$seq))==TRUE) {d$seq[which(d$seq=="ZSP")]<-"GASCALS"}
if(("GASCAL" %in% unique(d$seq))==TRUE) {d$seq[which(d$seq=="GASCAL")]<-"GASCALS"}
if(("GASCAL%" %in% unique(d$seq))==TRUE) {d$seq[which(d$seq=="GASCAL%")]<-"GASCALS%"}

# check number of sites..
if(length(unique(d$Site))>1) {
  stop("Multiple site codes are present in file under analysis. Only one site is allowed.", call. = FALSE)
}

## split data
gases <- unique(d$parameter)
phases <- c("SPAN", "PREC", "ZERO")
dat<-list()
dat.diff<-list()

# list of dataframes for raw responses
for(i in 1:length(gases)){
  for(j in 1:3){
    d %>% 
      filter(parameter == gases[i], seq == "GASCALS", phase == phases[j]) %>%
      select(date, response, true)-> dat[[((i-1)*3+j)]]
    names(dat)[[((i-1)*3+j)]]<-paste(gases[i], phases[j], sep="_")
  }
}

# list of dataframes of percent diffs
for(i in 1:length(gases)){
  for(j in 1:3){
    d %>% 
      filter(parameter == gases[i], seq == "GASCALS%", phase == phases[j]) %>%
      select(date, response, true)-> dat.diff[[((i-1)*3+j)]]
    names(dat.diff)[[((i-1)*3+j)]]<-paste(gases[i], phases[j], "diff", sep="_")
  }
}


##load site name...
sites<-data.frame(name=c("zAtas_cals", "zCP-cals", "zMB_cals", "zMesa_cals", "zNRP_cals", "xRH_cals"), 
                  site=c("Atascadero", "Carrizo Plain", "Morro Bay", "Mesa2", 
                         "Nipomo Regional Park", "Red Hills"),
                  stringsAsFactors = FALSE)

site<-sites$site[which(sites$name==d$site[1])]
date<-format(d$date[1], "%B %Y")

##clean-up
rm(d, sites, i, j, gases, filename, phases)

```

### Calibration Report for `r site`, `r date`.

`r comment`
```{r,echo=FALSE, warning=FALSE, message=FALSE, comment=""}

#functions for plotting
cal_plot<-function(param, title="vf"){
  
  #for moving legend outside of plot
  par(oma=c(0,0,0,5))
  
  #make some name for matching... param must be "O3CAL", "NO2CAL", ect...
  span<-paste(param, "SPAN", sep="_")
  prec<-paste(param, "PREC", sep="_")
  zero<-paste(param, "ZERO", sep="_")
  
  if(span %in% names(dat)){
    #plot span response and true
    subdat<-dat[[which(span==names(dat))]]
    plot(subdat$date, subdat$response, type="l",
         ylim=c(-5,1.1*max(subdat$true)),
         xlab="", ylab="ppb", main=title,
         las=2, xaxt="n",
         col="red", lty=1, lwd=2)
    axis(side=1, las=2, at=subdat$date[seq(1, 31, by=2)], 
         labels=format(subdat$date[seq(1, 31, by=2)], "%b %d"))
    lines(subdat$date, subdat$true,
          col="red", lty=2, lwd =1.5)
    
    #plot zero response and true
    subdat<-dat[[which(zero==names(dat))]]
    lines(subdat$date, subdat$response,
          col="green", lty=1, lwd=2)
    abline(h=0, lty=2)
    
    #plot prec
    subdat<-dat[[which(prec==names(dat))]]
    lines(subdat$date, subdat$response, 
         col="blue", lty=1, lwd=2)
    lines(subdat$date, subdat$true,
         col="blue", lty=2, lwd =1.5)
    
    par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
    plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
    #legend
    legend("right", legend=c("Span", "Precision", "Zero", "Response", "True"),
           lty=c(1,1,1,1,2), col=c("red", "blue", "green", 1,1), lwd=c(2,2,2,1.5,1.5), bty="n")
    
    par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(5, 4, 4, 2) + 0.1)


  }
}

cal_plot_diff<-function(param, title="vf"){
  
  #for moving legend outside of plot
  par(oma=c(0,0,0,5))
  
  #make some name for matching... param must be "O3CAL", "NO2CAL", ect...
  span<-paste(param, "SPAN", "diff", sep="_")
  prec<-paste(param, "PREC", "diff", sep="_")
  zero<-paste(param, "ZERO", "diff", sep="_")
  
    #plot QC limits
    if(param %in% c("O3CAL", "O3-cal")){
      QC<-c(3,5,7)
    } else {
      QC<-c(3,7,10)
    }
  
  if(span %in% names(dat.diff)){
    
    #find data
    subdat.s<-dat.diff[[which(span==names(dat.diff))]]
    subdat.z<-dat.diff[[which(zero==names(dat.diff))]]
    subdat.p<-dat.diff[[which(prec==names(dat.diff))]]
    
    #lims<-range(c(subdat.p$response, subdat.s$response, subdat.z$response))
    lims<-c(-1,1)*QC[3]
 
    #plot span response 
    plot(subdat.s$date, subdat.s$response, type="l",
         ylim=c(lims[1], lims[2]),
         xlab="", ylab="% error", main=title,
         las=2, xaxt="n",
         col="red", lty=1, lwd=2)
    axis(side=1, las=2, at=subdat.s$date[seq(1, 31, by=2)], 
         labels=format(subdat.s$date[seq(1, 31, by=2)], "%b %d"))
        
    #plot grid
    abline(h=0, lty=1)
    abline(h=(-15:15), lty=3, lwd=0.75)
    
    #plot zero response

    lines(subdat.z$date, subdat.z$response,
          col="green", lty=1, lwd=2)
    
    #plot prec

    lines(subdat.p$date, subdat.p$response, 
         col="blue", lty=1, lwd=2)
    
    #legend
    par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)  #for moving legend outside of plot
    plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")                       #for moving legend outside of plot
    legend("right", legend=c("Span", "Precision", "Zero"), lwd=2, col=c("red", "blue", "green"), bty="n")
    par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(5, 4, 4, 2) + 0.1)
  }
    
}


cal_plot_conv<-function(param, title="NOx Converter Efficiency"){
 
 #for moving legend outside of plot
  par(oma=c(0,0,0,5))
    
  #make some name for matching... param must be "O3CAL", "NO2CAL", ect...
  span<-paste(param, "SPAN", sep="_")
  prec<-paste(param, "PREC", sep="_")
  zero<-paste(param, "ZERO", sep="_")
  
  if(span %in% names(dat)){
    #plot span response and true
    subdat<-dat[[which(span==names(dat))]]
    plot(subdat$date, subdat$response, type="l",
         ylim=c(90,105),
         xlab="", ylab="%", main=title,
         las=2, xaxt="n",
         col="red", lty=1, lwd=2)
    axis(side=1, las=2, at=subdat$date[seq(1, 31, by=2)], 
         labels=format(subdat$date[seq(1, 31, by=2)], "%b %d"))
    
    
    #plot zero response and true
    subdat<-dat[[which(zero==names(dat))]]
    lines(subdat$date, subdat$response,
      col="green", lty=1, lwd=2)
    
    #plot prec
    subdat<-dat[[which(prec==names(dat))]]
    lines(subdat$date, subdat$response,
      col="blue", lty=1, lwd=2)
 
    #lines...
    abline(h=100, lty=2)
    abline(h=c(90,95,105), lty=3, lwd=0.75)
    abline(h=96, lty=3, col="red")
    
    #legend
    par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
    plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
    legend("right", legend=c("Average", "High", "Low", "Limit"),
           lty=c(1,1,1,3), col=c("green", "red", "blue", "red"), lwd=c(2,2,2,1), bty="n")
    par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(5, 4, 4, 2) + 0.1)

  }
}

```

```{r,echo=FALSE, warning=FALSE, message=FALSE, comment="", fig.width=8, fig.height = 4.5}
cal_plot("O3CAL", "Ozone Response")
cal_plot_diff("O3CAL", "Ozone Percent Error")
```

```{r,echo=FALSE, warning=FALSE, message=FALSE, comment="", fig.width=8, fig.height = 4.5}
cal_plot("NO2CAL", "NO2 Response")
cal_plot_diff("NO2CAL", "NO2 Percent Error")
```

```{r,echo=FALSE, warning=FALSE, message=FALSE, comment="", fig.width=8, fig.height = 4.5}
cal_plot("NOCAL", "NO Response")
cal_plot_diff("NOCAL", "NO Percent Error")
```

```{r,echo=FALSE, warning=FALSE, message=FALSE, comment="", fig.width=8, fig.height = 4.5}
cal_plot("NOXCAL", "NOx Response")
cal_plot_diff("NOXCAL", "NOx Percent Error")

```

```{r,echo=FALSE, warning=FALSE, message=FALSE, comment="", fig.width=8, fig.height = 4.5}
cal_plot_conv("NOXCony")

```

```{r,echo=FALSE, warning=FALSE, message=FALSE, comment="", fig.width=8, fig.height = 4.5}
cal_plot("SO2-CAL", "SO2 Response")
cal_plot_diff("SO2-CAL", "SO2 Percent Error")

```

#### Session Info
```{r, collapse = TRUE}
## generate list of files used, session info...
raw <- paste0(dir, params$filename)

cat("Report generated:", date(), "\n")
cat("Raw data file:", raw)
```
Reviewed by (signature/date): ______________________________
