---
output:
  html_document:
    theme: cerulean
    self_contained: true
params:
  directory:
    label: "Directory to look for data files:"
    value: "Desktop"
    input: radio
    choiceNames: ["../data", "Desktop", "Other - must specify full path in filename, below"]
    choiceValues: ["H: drive", "Desktop", "Other"]
  filename: 
    label: "AirVision filename:" 
    value: "BasicDataExportReport.csv"
  comment: 
    label: "Comment (optional):"
    value: ""
  ignore:
    label: "Run screen even on incomplete data?"
    value: FALSE
    input: radio
    choiceNames: ["Yes", "No"]
    choiceValues: [TRUE, FALSE]  
---

```{r global_options, echo=FALSE}

#for testing: dir <- "H: drive"; filename <- "AT-2017-01.csv"; comment <- ""; ignore <- FALSE
#for testing: metscreen("AT-2017-01.csv")

knitr::opts_knit$set(width=90)
knitr::opts_chunk$set(comment="", fig.width=8, fig.height = 5, echo = FALSE, 
                      warning=FALSE, message=FALSE )

filename <- params$filename
comment <- params$comment
dir <- params$directory

if(dir == "H: drive") dir <- paste0(getwd(), "/data/")
if(dir == "Desktop") {
  path <- strsplit(path.expand("~"), "/")[[1]]
  path <- path[1:(length(path)-1)]
  path <- paste(path, collapse = "/")
  dir <- paste(path, "Desktop/", sep = "/")
} 
if(dir == "Other") dir <- ""

```

```{r libraries}
library(dplyr, warn.conflicts=FALSE)
library(openair, warn.conflicts=FALSE)
```

```{r}
## Check inputs, load data:

# check AirVision file is present
if(!filename %in% list.files(dir)) {
  stop(paste0("File ", filename, " not found in ", dir, "."), call. = FALSE)
} 

# read file
d <- read.table(paste0(dir, filename), colClasses="character", header=F, sep=",")
  
# check for multiple sites
site <- unique(unlist(d[1,-1]))
if(length(site)!=1) {
  stop("Multiple site codes are present in file. Only one site is allowed.", call. = FALSE)
}

  
#check date range
dates<-as.POSIXct(d[-c(1:3),1], tz="UTC", format="%d-%b-%Y %H:%M")
month<-unique(format(dates, "%B"))
if(length(month)!=1) {stop ("All data must be from the same month.", call. = FALSE)}
  
#check for complete month of data:
if( month %in% month.name[c(1,3,5,7,8,10,12)] ){
   if(nrow(d)!=744+3 & ignore==F) stop("Month is incomplete. Set 'ignore=T' to run anyway.", call. = FALSE)
}
  
if( month == "February" ){
   if( nrow(d)!=672+3 & nrow(d)!=696+3 & ignore==F) {
     stop("Month is incomplete. Set 'ignore=T' to run anyway.", call. = FALSE)
   } 
}
  
if( month %in% month.name[c(4,6,9,11)] ){
  if(nrow(d)!=720+3 & ignore==F) stop("Month is incomplete. Set 'ignore=T' to run anyway.", call. = FALSE)
}

##format data
d <- d[-1, ] # get rid of site names header row...
vars <- tolower(d[1,])
if(("atm" %in% vars)==TRUE) {vars[match("atm", vars)] <- "amt"}
if(("ambtemp" %in% vars)==TRUE) {vars[match("ambtemp", vars)] <- "amt"}
if(("ozone" %in% vars)==TRUE) {vars[match("ozone", vars)] <- "o3"}
if(("pm10_contin" %in% vars)==TRUE) {vars[match("pm10_contin", vars)] <- "bam10"}
if(("pm10_std" %in% vars)==TRUE) {vars[match("pm10_std", vars)] <- "bam10std"}
if(("stm" %in% vars)==TRUE) {vars[match("stm", vars)] <- "rmt"}
if(("sigtheta" %in% vars)==TRUE) {vars[match("sigtheta", vars)] <- "sigt"}
if(("vwsp" %in% vars)==TRUE) {vars[match("vwsp", vars)] <- "wsv"}
if(("vwdr" %in% vars)==TRUE) {vars[match("vwdr", vars)] <- "wdv"}
if(("wdr" %in% vars)==TRUE) {vars[match("wdr", vars)]<-"wdv"}

vars[1] <- "date"
names(d) <- vars
d <- d[-c(1,2),]
n.param <- length(vars)
d[,2:n.param] <- apply(d[,2:n.param], 2, as.numeric)
d$date <- dates

## check that at wsv, wdv, and sigt are present:
if (sum(c("wsv", "wdv", "sigt") %in% vars)!=3) {
  stop("WSV, WDV, and SIGT must all be present", call. = FALSE)
  }

```

## Meteorology Screen for `r site`, `r format(d$date[1], "%B %Y")`.

`r comment`

```{r}

##identify which archival data to use:
sitelist<-c("Atascadero", "Carrizo Plains School","CDF", "Grover Beach", "Mesa 2", "MORRO BAY", 
            "Nipomo Regional Park", "RED HILLS", "OFS")
  #sitelist = the names that airvions uses and will be in BasicDataExportReport

archlist<-c("arch-atas.csv", "arch-carr.csv", "arch-cdf.csv", "arch-grov.csv", "arch-mesa.csv",
            "arch-morro.csv", "arch-nrp.csv", "arch-red.csv", "arch-oso.csv")

old<-archlist[[match(site, sitelist)]]    #select archive to load
old<-read.csv(old, stringsAsFactors = FALSE) #read it
old$date<-as.POSIXct(old$date, format="%Y-%m-%d %H:%M:%S", tz="UTC")
old$month<-format(old$date, "%m")
old$year<-format(old$date, "%Y")

## need this for later
monthid<-format(d$date[1], "%m")
```

```{r}
if("amt" %in% names(d) & "amt" %in% names(old)) {
  j<-"amt"
  
  old %>%                        
    filter(month==format(d$date[1], "%m"))  %>%
    select(matches(j), year) -> old.sub 
    
  ## get current data filtered
  d$year<-format(d$date, "%Y")
  d %>%
    select(matches(j),year) -> d.sub
  
  ##if all data is NA, print message
  if(sum(is.na(d.sub[,1]))==nrow(d.sub)){
    cat("NOTE: all", toupper(j), " data for this month at this site is either missing or invalid")
  }

  ##create unified dataframe
  sub<-rbind(old.sub, d.sub)

  #plot it!
  boxplot(sub[,j]~sub$year, main=paste(toupper(j), "at", site, "for", format(d$date[1], "%B")), 
          las=2, varwidth=TRUE,
          xlab = "", ylab = "")

}

```

```{r}

##generate boxplots of met params.
for(j in c("wsv","sigt")){

  ## filter arch data to select only one param and on month
  old %>%                        
    filter(month==format(d$date[1], "%m"))  %>%
    select(matches(j), year) -> old.sub 
    
  ## get current data filtered
  d$year<-format(d$date, "%Y")
  d %>%
    select(matches(j),year) -> d.sub
  
  ##if all data is NA, print message
  if(sum(is.na(d.sub[,1]))==nrow(d.sub)){
    cat("NOTE: All", toupper(j), " data for this month at this site is either missing or invalid.")
  }

  ##create unified dataframe
  sub<-rbind(old.sub, d.sub)

  #plot it!
  boxplot(sub[,j]~sub$year, main=paste(toupper(j), "at", site, "for", format(d$date[1], "%B")), las=2,
          xlab = "", ylab = "")
}
```

------
### Wind Roses
```{r, echo=FALSE, comment="", fig.width=8, fig.height = 5}

old %>%
  filter(month==format(d$date[1], "%m")) %>%
  select(ws=wsv, wd=wdv, date) -> old.sub

d %>%
  select(ws=wsv, wd=wdv, date) -> d.sub

##if all data is NA, print message
if(sum(is.na(d.sub$ws))==nrow(d.sub)){
    cat("NOTE: All wind data for this month at this site is either missing or invalid.")
}

sub<-rbind(old.sub, d.sub)

openair::windRose(sub, main=paste("Wind Roses for the month of", format(d$date[1], "%B")), type="year", 
         paddle=FALSE, key.position="right", annotate = FALSE,
         key = list(footer="mph"), breaks=c(0, 3,6, 9, 12), grid.line=10)

```

### Session Info
```{r, collapse = TRUE}
## generate list of files used, session info...
raw <- paste0(dir, params$filename)

cat("Report generated:", date(), "\n")
cat("Raw data file:", raw)
```

Reviewed by (signature/date): ______________________________
